
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Sep 23 15:35:26 MDT 2016
//----------------------------------------------------

package lex;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 32;
  public static final int FUNCTION = 29;
  public static final int Y = 16;
  public static final int PUNTOYCOMA = 8;
  public static final int PROGRAMA = 52;
  public static final int ENTERO = 2;
  public static final int CASE = 48;
  public static final int O = 17;
  public static final int RESTA = 35;
  public static final int MOSTRARMENSAJE = 43;
  public static final int REPEAT = 41;
  public static final int FIN = 22;
  public static final int FOR = 24;
  public static final int WRITE = 51;
  public static final int NOT = 56;
  public static final int AND = 55;
  public static final int CAD = 3;
  public static final int MAYORQUE = 12;
  public static final int IGUAL = 13;
  public static final int CARACTER = 4;
  public static final int OR = 54;
  public static final int BEGIN = 21;
  public static final int UNTIL = 42;
  public static final int SUMA = 33;
  public static final int IF = 19;
  public static final int ID = 39;
  public static final int PARENTESISIZQ = 30;
  public static final int OF = 49;
  public static final int EOF = 0;
  public static final int ASIG = 53;
  public static final int TRUE = 46;
  public static final int MAYORIGUALQUE = 9;
  public static final int error = 1;
  public static final int COMA = 15;
  public static final int CADENA = 40;
  public static final int MODULO = 57;
  public static final int NEGACION = 18;
  public static final int REALNUM = 38;
  public static final int ERROR = 47;
  public static final int BOLEANO = 5;
  public static final int REAL = 6;
  public static final int MENORQUE = 11;
  public static final int DISTINTODE = 14;
  public static final int ELSE = 23;
  public static final int PUNTO = 45;
  public static final int READ = 50;
  public static final int TO = 25;
  public static final int WHILE = 27;
  public static final int THEN = 20;
  public static final int MENORIGUALQUE = 10;
  public static final int PARENTESISDER = 31;
  public static final int FALSE = 44;
  public static final int DIVISION = 36;
  public static final int VAR = 7;
  public static final int PROCEDURE = 28;
  public static final int INTEGERNUM = 37;
  public static final int DO = 26;
  public static final int MULTIPLICACION = 34;
}

